In [3]:
import pandas as pd

In [7]:
df = pd.read_csv("/content/diabetes.csv")

In [8]:
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1
5,5,116,74.0,27,102.5,25.6,0.201,30,0
6,3,78,50.0,32,88.0,31.0,0.248,26,1
7,10,115,70.0,27,102.5,35.3,0.134,29,0
8,2,197,70.0,45,543.0,30.5,0.158,53,1
9,8,125,96.0,32,169.5,34.3,0.232,54,1

In [10]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure               float64
SkinThickness                 int64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 54.1 KB

In [12]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.677083,72.389323,29.089844,141.753906,32.434635,0.471876,33.240885,0.348958
std,3.369578,30.464161,12.106039,8.890820,89.100847,6.880498,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,25.000000,102.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,28.000000,102.500000,32.050000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,169.500000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

Check Data Quality

In [17]:
#check for missisng values

In [13]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [16]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.nunique()

Pregnancies                  17
Glucose                     135
BloodPressure                47
SkinThickness                50
Insulin                     187
BMI                         247
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [21]:
df['Age'].unique()

array([50, 31, 32, 21, 33, 30, 26, 29, 53, 54, 34, 57, 59, 51, 27, 41, 43,
       22, 38, 60, 28, 45, 35, 46, 56, 37, 48, 40, 25, 24, 58, 42, 44, 39,
       36, 23, 61, 69, 62, 55, 65, 47, 52, 66, 49, 63, 67, 72, 81, 64, 70,
       68])

In [22]:
df['BMI'].unique()

array([33.6, 26.6, 23.3, 28.1, 43.1, 25.6, 31. , 35.3, 30.5, 34.3, 37.6,
       38. , 27.1, 30.1, 25.8, 30. , 45.8, 29.6, 43.3, 34.6, 39.3, 35.4,
       39.8, 29. , 36.6, 31.1, 39.4, 23.2, 22.2, 34.1, 36. , 31.6, 24.8,
       19.9, 27.6, 24. , 33.2, 32.9, 38.2, 37.1, 34. , 40.2, 22.7, 45.4,
       27.4, 42. , 29.7, 28. , 39.1, 19.4, 24.2, 24.4, 33.7, 34.7, 23. ,
       37.7, 46.8, 40.5, 41.5, 25. , 25.4, 32.8, 32.5, 42.7, 19.6, 28.9,
       28.6, 43.4, 35.1, 32. , 24.7, 32.6, 43.2, 22.4, 29.3, 24.6, 48.8,
       32.4, 38.5, 26.5, 19.1, 46.7, 23.8, 33.9, 20.4, 28.7, 49.7, 39. ,
       26.1, 22.5, 39.6, 29.5, 37.4, 33.3, 31.2, 28.2, 53.2, 34.2, 26.8,
       55. , 42.9, 34.5, 27.9, 38.3, 21.1, 33.8, 30.8, 36.9, 39.5, 27.3,
       21.9, 40.6, 47.9, 50. , 25.2, 40.9, 37.2, 44.2, 29.9, 31.9, 28.4,
       43.5, 32.7, 67.1, 45. , 34.9, 27.7, 35.9, 22.6, 33.1, 30.4, 52.3,
       24.3, 22.9, 34.8, 30.9, 40.1, 23.9, 37.5, 35.5, 42.8, 42.6, 41.8,
       35.8, 37.8, 28.8, 23.6, 35.7, 36.7, 45.2, 44. , 46.2, 35. , 43.6,
       44.1, 18.4, 29.2, 25.9, 32.1, 36.3, 40. , 25.1, 27.5, 45.6, 27.8,
       24.9, 25.3, 37.9, 27. , 26. , 38.7, 20.8, 36.1, 30.7, 32.3, 52.9,
       21. , 39.7, 25.5, 26.2, 19.3, 38.1, 23.5, 45.5, 23.1, 39.9, 36.8,
       21.8, 41. , 42.2, 34.4, 27.2, 36.5, 29.8, 39.2, 38.4, 36.2, 48.3,
       20. , 22.3, 45.7, 23.7, 22.1, 42.1, 42.4, 18.2, 26.4, 45.3, 37. ,
       24.5, 32.2, 59.4, 21.2, 26.7, 30.2, 46.1, 41.3, 38.8, 35.2, 42.3,
       40.7, 46.5, 33.5, 37.3, 30.3, 26.3, 21.7, 36.4, 28.5, 26.9, 38.6,
       31.3, 19.5, 20.1, 40.8, 23.4, 28.3, 38.9, 57.3, 35.6, 49.6, 44.6,
       24.1, 44.5, 41.2, 49.3, 46.3])

In [23]:
(df['Glucose']==0).sum()

np.int64(0)

In [24]:
df.isin([0]).sum()

Pregnancies                 111
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                       0
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [28]:
(df[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']]==0).sum()

Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
dtype: int64

Selecting and Filtering Data

In [33]:
 #selecting single column
df['Glucose']

0      148
1       85
2      183
3       89
4      137
      ...
763    101
764    122
765    121
766    126
767     93
Name: Glucose, Length: 768, dtype: int64

In [34]:
#selecting multiple columns
df[['Glucose','BMI','Age']]

     Glucose   BMI  Age
0        148  33.6   50
1         85  26.6   31
2        183  23.3   32
3         89  28.1   21
4        137  43.1   33
..       ...   ...  ...
763      101  32.9   63
764      122  36.8   27
765      121  26.2   30
766      126  30.1   47
767       93  30.4   23

[768 rows x 3 columns]

In [36]:
df[df['Age']>50]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70.0,45,543.0,30.5,0.158,53,1
9,8,125,96.0,32,169.5,34.3,0.232,54,1
12,10,139,80.0,27,102.5,27.1,1.441,57,0
13,1,189,60.0,23,846.0,30.1,0.398,59,1
14,5,166,72.0,19,175.0,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
719,5,97,76.0,27,169.5,35.6,0.378,52,1
734,2,105,75.0,27,102.5,23.3,0.560,53,0
757,0,123,72.0,32,169.5,36.3,0.258,52,1
759,6,190,92.0,32,169.5,35.5,0.278,66,1
763,10,101,76.0,48,180.0,32.9,0.171,63,0

In [40]:
#Filter rows and with multiple conditions
df[(df['Age']>50) & (df['Outcome'] == 1)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70.0,45,543.0,30.5,0.158,53,1
9,8,125,96.0,32,169.5,34.3,0.232,54,1
13,1,189,60.0,23,846.0,30.1,0.398,59,1
14,5,166,72.0,19,175.0,25.8,0.587,51,1
24,11,143,94.0,33,146.0,36.6,0.254,51,1
39,4,111,72.0,47,207.0,37.1,1.390,56,1
43,9,171,110.0,24,240.0,45.4,0.721,54,1
53,8,176,90.0,34,300.0,33.7,0.467,58,1
93,4,134,72.0,32,169.5,23.8,0.277,60,1
115,4,146,92.0,32,169.5,31.2,0.539,61,1
129,0,105,84.0,32,169.5,27.9,0.741,62,1
186,8,181,68.0,36,495.0,30.1,0.615,60,1
206,8,196,76.0,29,280.0,37.5,0.605,57,1
207,5,162,104.0,32,169.5,37.7,0.151,52,1
221,2,158,90.0,32,169.5,31.6,0.805,66,1
236,7,181,84.0,21,192.0,35.9,0.586,51,1
259,11,155,76.0,28,150.0,33.3,1.353,51,1
284,2,108,80.0,32,169.5,27.0,0.259,52,1
319,6,194,78.0,32,169.5,23.5,0.129,59,1
363,4,146,78.0,32,169.5,38.5,0.520,67,1
375,12,140,82.0,43,325.0,39.2,0.528,58,1
388,5,144,82.0,26,285.0,32.0,0.452,58,1
458,10,148,84.0,48,237.0,37.6,1.001,51,1
498,7,195,70.0,33,145.0,25.1,0.163,55,1
516,9,145,88.0,34,165.0,30.3,0.771,53,1
542,10,90,85.0,32,169.5,34.9,0.825,56,1
546,5,187,76.0,27,207.0,43.6,1.034,53,1
560,6,125,76.0,32,169.5,33.8,0.121,54,1
579,2,197,70.0,99,169.5,34.7,0.575,62,1
584,8,124,76.0,24,600.0,28.7,0.687,52,1
588,3,176,86.0,27,156.0,33.3,1.154,52,1
603,7,150,78.0,29,126.0,35.2,0.692,54,1
666,4,145,82.0,18,169.5,32.5,0.235,70,1
676,9,156,86.0,32,169.5,24.8,0.230,53,1
702,1,168,88.0,29,169.5,35.0,0.905,52,1
719,5,97,76.0,27,169.5,35.6,0.378,52,1
757,0,123,72.0,32,169.5,36.3,0.258,52,1
759,6,190,92.0,32,169.5,35.5,0.278,66,1

In [43]:
#Access rows by index (iloc)
df.iloc[10:15]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
10,4,110,92.0,27,102.5,37.6,0.191,30,0
11,10,168,74.0,32,169.5,38.0,0.537,34,1
12,10,139,80.0,27,102.5,27.1,1.441,57,0
13,1,189,60.0,23,846.0,30.1,0.398,59,1
14,5,166,72.0,19,175.0,25.8,0.587,51,1

Sorting & Grouping

In [52]:
df.sort_values(by='Age',ascending=True).tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
123,5,132,80.0,27,102.5,26.8,0.186,69,0
684,5,136,82.0,27,102.5,30.1,0.640,69,0
666,4,145,82.0,18,169.5,32.5,0.235,70,1
453,2,119,70.0,27,102.5,19.6,0.832,72,0
459,9,134,74.0,33,60.0,25.9,0.460,81,0

In [44]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

Group by and aggregate

In [47]:
df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,110.622000,70.844000,27.170000,117.172000,30.846000,0.429734,31.190000
1,4.865672,142.302239,75.272388,32.671642,187.615672,35.398507,0.550500,37.067164

In [48]:
df['BMI'].mean()

np.float64(32.434635416666666)

In [49]:
df['Glucose'].mean()

np.float64(121.67708333333333)

In [50]:
df['Glucose'].median()

117.0

In [53]:
df['Age'].mode()

0    22
Name: Age, dtype: int64

In [54]:
df['Age'].value_counts()

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
36    16
38    16
32    16
45    15
34    14
46    13
40    13
43    13
39    12
35    10
44     8
50     8
51     8
52     8
58     7
54     6
47     6
49     5
60     5
53     5
57     5
48     5
63     4
66     4
55     4
62     4
59     3
56     3
65     3
67     3
61     2
69     2
72     1
81     1
64     1
70     1
68     1
Name: count, dtype: int64

In [61]:
age_mode = df['Age'].mode()[0]

In [64]:
age_mode

np.int64(22)

In [66]:
(df['Age']==df['Age'].mode()[0]).sum()

np.int64(72)

In [67]:
df['Age'].std()

11.76023154067868

In [69]:
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.130155,0.209151,0.089028,0.058767,0.023890,-0.033523,0.544341,0.221898
Glucose,0.130155,1.000000,0.225141,0.229289,0.490015,0.236171,0.138353,0.268910,0.495990
BloodPressure,0.209151,0.225141,1.000000,0.199349,0.070128,0.286399,-0.001443,0.325135,0.174469
SkinThickness,0.089028,0.229289,0.199349,1.000000,0.200129,0.566086,0.106280,0.129537,0.295138
Insulin,0.058767,0.490015,0.070128,0.200129,1.000000,0.238443,0.146878,0.123629,0.377081
BMI,0.023890,0.236171,0.286399,0.566086,0.238443,1.000000,0.152771,0.027849,0.315577
DiabetesPedigreeFunction,-0.033523,0.138353,-0.001443,0.106280,0.146878,0.152771,1.000000,0.033561,0.173844
Age,0.544341,0.268910,0.325135,0.129537,0.123629,0.027849,0.033561,1.000000,0.238356
Outcome,0.221898,0.495990,0.174469,0.295138,0.377081,0.315577,0.173844,0.238356,1.000000